apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer            # Exposed to internet via AWS ELB
  selector:
    app: vote-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP